
kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta1 
metadata: 
  name: joomla
spec: 
  maxReplicas: 6 
  minReplicas: 1 
  scaleTargetRef: 
    apiVersion: app/v1 
    kind: Deployment 
    name: joomla
  metrics: 
  - type: Resource 
    resource: 
      name: cpu 
      targetAverageUtilization: 50
