apiVersion: v1
kind: Service
metadata:
  name: joomla-svc
  labels:
    app: joomla
    tier: frontend
    env: test
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: joomla
    tier: frontend
    env: test
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla-dep
  labels:
    app: joomla
    tier: frontend
    env: test
spec:
  selector:
    matchLabels:
      app: joomla
      tier: frontend
      env: test
  template:
    metadata:
      labels:
        app: joomla
        tier: frontend
        env: test
    spec:
      containers:
      - image: bitnami/joomla:latest 
        name: varjoomla
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "1"
        - name: JOOMLA_DATABASE_TYPE
          value: mysqli
        - name: JOOMLA_DATABASE_USER
          value: root
        - name: JOOMLA_DATABASE_NAME
          value: joomla      
        - name: MARIADB_HOST
          value: mysql-svc 
        ports:
        - containerPort: 8080
          name: http
